//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceAnswers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChoiceAnswers()
        {
            this.StudentsChoices = new HashSet<StudentsChoices>();
        }
    
        public int id { get; set; }
        public int question_id { get; set; }
        public Nullable<int> album_id { get; set; }
        public string text { get; set; }
        public bool is_correct { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Questions Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsChoices> StudentsChoices { get; set; }
    }
}
