//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int id { get; set; }
        public int album_id { get; set; }
        public string title { get; set; }
        public string pathname { get; set; }
    
        public virtual Albums Albums { get; set; }
    }
}
