//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTexts
    {
        public int id { get; set; }
        public int result_id { get; set; }
        public int text_answer_id { get; set; }
        public string text_answer { get; set; }
        public int number { get; set; }
    
        public virtual Results Results { get; set; }
        public virtual TextAnswers TextAnswers { get; set; }
    }
}
